baseURL: https://www.xxrbear.cn
languageCode: zh
defaultContentLanguage: zh
title: 熊大如如的猪窝
theme: hugo-PaperMod

enableInlineShortcodes: true
enableEmoji: true
enableRobotsTXT: true

hasCJKLanguage: true

buildDrafts: false
buildFuture: false
buildExpired: false

paginate: 10 

minify:
  disableXML: true

permalinks:
  post: "/:title/"

languages:
  zh:
    languageName: "Chinese"
    weight: 1
    profileMode:
      enabled: true
      title: 合抱之木 生于毫末
      imageUrl: "dog.jpg"
      imageTitle:
      imageWidth: 150
      imageHeight: 150
      buttons:
        - name: ️技术
          url: posts/tech
        - name: 阅读
          url: posts/read
        - name: ️随笔
          url: posts/life
    menu:
      main:
        - identifier: search
          name: 搜索
          url: search
          weight: 1
        - identifier: home
          name: 主页
          url: /
          weight: 2
        - identifier: tags
          name: 标签
          url: tags
          weight: 40
        - identifier: archives
          name: ️归档
          url: archives/
          weight: 20
        - identifier: about
          name: 关于
          url: about
          weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  author: 熊大如如

  defaultTheme: light
  disableThemeToggle: false
  DateFormat: "2006-01-02"
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false # 隐藏页脚
  ShowWordCounts: true
  VisitCount: true

  ShowLastMod: true #显示文章更新时间

  comments: true

  socialIcons:
    - name: github
      url: "https://github.com/xxrBear"
    - name: email
      url: "mailto:xxrBear@gmail.com"
    - name: RSS
      url: "index.xml"

  assets:
    favicon: "dog.ico"

  fuseOpts: # 搜索配置
    isCaseSensitive: true
    shouldSort: true
    location: 0
    distance: 300
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary"]

  utteranc:
    enable: enable # 是否启用 utteranc 评论
    repo: "xxrBear/blog-posts" # github repo
    issueTerm: "pathname" # 选择评论的方式，pathname：使用路径作为 issue 的唯一标识符，title：使用标题作为 issue 的唯一标识符
    theme: "github-light"

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true # HUGO 默认转义 Markdown 文件中的 HTML 代码，如需开启的话
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false # 关闭代码行行号显示
    style: darcula
